- name: variable
  hosts: local
  connection: local
  vars: # play level variables
    COURSE: "Devops with AWS"
    DURATION: 120hours
    TRAINER: sivakumar
  tasks:
  - name: print the variable
    vars: # task level variables, accessible only with in the task. Task variables can override play level variables
      COURSE: Ansible
    ansible.builtin.debug:
     msg: "Course is {{COURSE}}, Duration is {{DURATION}}, Trainer is {{TRAINER}}"

  - name: print the variable
    ansible.builtin.debug:
     msg: "Course is {{COURSE}}, Duration is {{DURATION}}, Trainer is {{TRAINER}}"